Quell compiler warning: unsed result.
Build will fail if warnings are treated as errors due to:

    relayd/route.c:45:2: error: ignoring return value of ‘write’, declared with \
    attribute warn_unused_result [-Werror=unused-result]
      write(fd, "-1", 2);
      ^
    cc1: all warnings being treated as errors

Signed-off-by: Theodore A. Roth <theodore_roth@trimble.com>